# Generated by Django 5.1.4 on 2025-07-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='causes/'),
        ),
    ]
